repository:
  has_issues: true
  has_projects: true
  has_wiki: false
  has_downloads: true
  default_branch: main

labels:
  - name: bug
    color: d73a4a
    description: Something isn't working
  - name: dependencies
    color: 0366d6
    description: Pull requests that update a dependency file
  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation
  - name: feature request
    color: C1117B
    description: Suggest an idea for future development
  - name: question
    color: 813195
    description: Further information is requested


